# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messages.proto',
  package='ffrkx.proto',
  serialized_pb=_b('\n\x0emessages.proto\x12\x0b\x66\x66rkx.proto\"5\n\x0c\x46\x46RKResponse\x12\x14\n\x0crequest_path\x18\x01 \x02(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x02(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_FFRKRESPONSE = _descriptor.Descriptor(
  name='FFRKResponse',
  full_name='ffrkx.proto.FFRKResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_path', full_name='ffrkx.proto.FFRKResponse.request_path', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='content', full_name='ffrkx.proto.FFRKResponse.content', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=84,
)

DESCRIPTOR.message_types_by_name['FFRKResponse'] = _FFRKRESPONSE

FFRKResponse = _reflection.GeneratedProtocolMessageType('FFRKResponse', (_message.Message,), dict(
  DESCRIPTOR = _FFRKRESPONSE,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:ffrkx.proto.FFRKResponse)
  ))
_sym_db.RegisterMessage(FFRKResponse)


# @@protoc_insertion_point(module_scope)
